### PR TITLE
Generate hreflang Tags for all stores

### PR DESCRIPTION
**Pull request by avstudnitz**
Supported for product pages, category pages and cms pages.

### CODE REVIEW

**Comment by avstudnitz** [comment]
Will fix the tests tomorrow. Didn't realise there were any.

**Comment by avstudnitz** [comment]
Ignoring the Codacy results as I don't agree that variable names should by < 20 chars. Everything else fixed.

**Comment by avstudnitz** [comment]
@mhauri Could you check it, or should I assign it to @jalogut?

**Comment by mhauri** [comment]
@avstudnitz thank you, yes have to adapt the settings for variable names.

**Pull request merged**
